#!/bin/bash

## Open links in firefox
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=`which eww`
cmd="firefox --new-tab"

close_dash() {
	${EWW} --config "$CFG" close \
					profile system clock uptime music social \
					weather apps logout sleep reboot poweroff folders
	rm -rf "$FILE"
}

if [[ "$1" == "--gh" ]]; then
	close_dash && ${cmd} "https://github.com"

elif [[ "$1" == "--rd" ]]; then
	close_dash && ${cmd} "https://reddit.com"

elif [[ "$1" == "--tw" ]]; then
	close_dash && ${cmd} "https://twitter.com"

elif [[ "$1" == "--yt" ]]; then
	close_dash && ${cmd} "https://youtube.com"

elif [[ "$1" == "--bs" ]]; then
	close_dash && ${cmd} "https://bsky.app"

elif [[ "$1" == "--md" ]]; then
	close_dash && ${cmd} "https://defcon.social"

fi
