#!/bin/bash

## Open Applications
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=`which eww`

close_dash() {
	${EWW} --config "$CFG" close \
					profile system clock uptime music social \
					weather apps logout sleep reboot poweroff folders vpn
	rm -rf "$FILE"
}

if [[ "$1" == "--ff" ]]; then
	close_dash && firefox &

elif [[ "$1" == "--tg" ]]; then
	close_dash && telegram-desktop &

elif [[ "$1" == "--dc" ]]; then
	close_dash && discord &

elif [[ "$1" == "--tr" ]]; then
	close_dash && alacritty --working-directory ~ &

elif [[ "$1" == "--fm" ]]; then
	close_dash && thunar ~ &

elif [[ "$1" == "--ge" ]]; then
	close_dash && geany &

elif [[ "$1" == "--cd" ]]; then
	close_dash && code &

elif [[ "$1" == "--gp" ]]; then
	close_dash && gimp &

elif [[ "$1" == "--vb" ]]; then
	close_dash && virtualbox &

elif [[ "$1" == "--ob" ]]; then
	close_dash && obsidian &

elif [[ "$1" == "--gt" ]]; then
	close_dash && ghostty &

elif [[ "$1" == "--steam" ]]; then
	close_dash && steam &

elif [[ "$1" == "--gfn" ]]; then
	close_dash && /usr/bin/chromium --profile-directory=Default --app-id=egmafekfmcnknbdlbfbhafbllplmjlhn &

elif [[ "$1" == "--plex" ]]; then
	close_dash && flatpak run tv.plex.PlexDesktop &

fi
