# Hibernate mode: lock and turn off screens quickly, then hibernate
# System fully powers down to disk after a few minutes

general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 60  # 1 min
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 90  # 1.5 min
    on-timeout = loginctl lock-session
}

listener {
    timeout = 300  # 5 min
    on-timeout = systemctl hibernate
}
